### PR TITLE
Lower ordinal priority of page decorator

### PR DESCRIPTION
**Pull request by jvz**
Combined with JENKINS-54325 and https://github.com/jenkinsci/jenkins/pull/3721, this fixes the known issue of the login and
signup pages not looking right.

Signed-off-by: Matt Sicker <boards@gmail.com>

@reviewbybees

### CODE REVIEW

**Comment by Wadeck** [comment]
@jvz tests need to be fixed, I imagine is the version of the core that is no longer sync-up

**Comment by jvz** [comment]
The test is failing correctly; it'll work again once this PR is updated to be based on the Jenkins core version fixed in the referenced PR.

**Comment by Wadeck** [comment]
@jvz do you want to merge it like that or wait for that PR to be merged and then publish an incremental of core to see the tests passing?

**Comment by jvz** [comment]
I'll rebuild the upstream PR to try to get an incremental release. The previous build had a flaky test fail it looks like, so no incremental was published. Then I can update this PR with that version.

**Pull request merged**
